/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fin_httrader_utils_win32_HtQuikListener */

#ifndef _Included_com_fin_httrader_utils_win32_HtQuikListener
#define _Included_com_fin_httrader_utils_win32_HtQuikListener
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_fin_httrader_utils_win32_HtQuikListener
 * Method:    init
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_fin_httrader_utils_win32_HtQuikListener_init
  (JNIEnv *, jobject);

/*
 * Class:     com_fin_httrader_utils_win32_HtQuikListener
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fin_httrader_utils_win32_HtQuikListener_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
/* Header for class com_fin_httrader_utils_win32_HtQuikListener_ListenerInterface */

#ifndef _Included_com_fin_httrader_utils_win32_HtQuikListener_ListenerInterface
#define _Included_com_fin_httrader_utils_win32_HtQuikListener_ListenerInterface
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
