/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry */

#ifndef _Included_com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry
#define _Included_com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_BID
#define com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_BID -1L
#undef com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_ASK
#define com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_ASK 1L
#undef com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_DUMMY
#define com_fin_httrader_utils_hlpstruct_HtLevel2Data_Htlevel2Entry_IS_DUMMY 0L
#ifdef __cplusplus
}
#endif
#endif
