/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HtWorkInProgress2.java
 *
 * Created on 07.09.2010, 22:01:49
 */
package htrangebreaker.utils.gui;

import htrangebreaker.utils.ProgressDialogInterface;
import java.awt.AWTEvent;
import java.awt.ActiveEvent;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.EventQueue;
import java.awt.MenuComponent;
import java.awt.event.MouseEvent;
import javax.swing.SwingUtilities;
import org.jdesktop.application.Action;

/**
 *
 * @author DanilinS
 */
public class HtWorkInProgress2 extends javax.swing.JInternalFrame {

	private ProgressDialogInterface pdint_m = null;
	private boolean modal = false;
	private String message_m = null;

	// ---------------------------
	/** Creates new form HtWorkInProgress2 */
	public HtWorkInProgress2() {
		initComponents();
		
	}

	@Override
	public void show() {
		super.show();
		if (this.modal) {
			startModal();
		}
	}

	@Override
	public void setVisible(boolean value) {
		super.setVisible(value);


		if (modal) {
			if (value) {
				startModal();
			} else {
				stopModal();
			}
		}
	}

	private synchronized void startModal() {

		try {
			if (message_m != null) {
						jLabel2.setText(message_m);
			}

			centerParent();
			requestFocus();

			if (SwingUtilities.isEventDispatchThread()) {
				EventQueue theQueue = getToolkit().getSystemEventQueue();
				while (isVisible()) {
					AWTEvent event = theQueue.getNextEvent();
					Object source = event.getSource();
					boolean dispatch = true;

					if (event instanceof MouseEvent) {
						MouseEvent e = (MouseEvent) event;
						MouseEvent m = SwingUtilities.convertMouseEvent((Component) e.getSource(), e, this);
						if (!e.getSource().getClass().getName().equals("javax.swing.Popup$HeavyWeightWindow") &&
							!this.contains(m.getPoint()) && e.getID() != MouseEvent.MOUSE_DRAGGED && e.getID() != MouseEvent.MOUSE_RELEASED) {
							dispatch = false;
						}

					}

					if (dispatch) {
						if (event instanceof ActiveEvent) {
							((ActiveEvent) event).dispatch();
						} else if (source instanceof Component) {
							((Component) source).dispatchEvent(
											event);
						} else if (source instanceof MenuComponent) {
							((MenuComponent) source).dispatchEvent(
											event);
						} else {
							System.err.println(
											"Unable to dispatch: " + event);
						}
					}
				}
			} else {
				while (isVisible()) {
					wait();
				}
			}
		} catch (InterruptedException ignored) {
		}

	}

	private synchronized void stopModal() {
		notifyAll();
	}

	public void setModal(boolean modal) {
		this.modal = modal;
	}

	public boolean isModal() {
		return this.modal;
	}

	public void initialize(ProgressDialogInterface pdint, String message) {
		pdint_m = pdint;
		message_m = message;
	}

	public void reset()
	{
		pdint_m = null;
		message_m = null;
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jPanel1 = new javax.swing.JPanel();
    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jCancelBtn = new javax.swing.JButton();

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(htrangebreaker.HtRangeBreakerApp.class).getContext().getResourceMap(HtWorkInProgress2.class);
    setTitle(resourceMap.getString("Form.title")); // NOI18N
    setName("Form"); // NOI18N

    jPanel1.setBackground(resourceMap.getColor("jPanel1.background")); // NOI18N
    jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    jPanel1.setName("jPanel1"); // NOI18N

    jLabel1.setName("jLabel1"); // NOI18N

    jLabel2.setText(resourceMap.getString("jLabel2.text")); // NOI18N
    jLabel2.setName("jLabel2"); // NOI18N

    javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(htrangebreaker.HtRangeBreakerApp.class).getContext().getActionMap(HtWorkInProgress2.class, this);
    jCancelBtn.setAction(actionMap.get("onCancel")); // NOI18N
    jCancelBtn.setText(resourceMap.getString("jCancelBtn.text")); // NOI18N
    jCancelBtn.setName("jCancelBtn"); // NOI18N

    javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
    jPanel1.setLayout(jPanel1Layout);
    jPanel1Layout.setHorizontalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(115, 115, 115)
            .addComponent(jLabel1))
          .addGroup(jPanel1Layout.createSequentialGroup()
            .addGap(101, 101, 101)
            .addComponent(jCancelBtn)))
        .addContainerGap())
    );
    jPanel1Layout.setVerticalGroup(
      jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(jPanel1Layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel2)
        .addGap(18, 18, 18)
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
        .addComponent(jCancelBtn)
        .addContainerGap())
    );

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

	
	private void centerParent() {
		Dimension d = getToolkit().getScreenSize();
		setLocation(d.width / 3, d.height / 3);

	}

	@Action
	public void onCancel() {
		if (pdint_m != null) {
			pdint_m.onCancel();
		}
	}

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jCancelBtn;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JPanel jPanel1;
  // End of variables declaration//GEN-END:variables
}
