/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_fin_httrader_utils_Uid */

#ifndef _Included_com_fin_httrader_utils_Uid
#define _Included_com_fin_httrader_utils_Uid
#ifdef __cplusplus
extern "C" {
#endif
#undef com_fin_httrader_utils_Uid_LENGTH
#define com_fin_httrader_utils_Uid_LENGTH 16L
/*
 * Class:     com_fin_httrader_utils_Uid
 * Method:    generateUniqueUid
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_fin_httrader_utils_Uid_generateUniqueUid
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
