/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * HtTextBox.java
 *
 * Created on 25.01.2010, 13:48:10
 */

package com.fin.htraderhelper;


import com.fin.htraderhelper.utils.*;
import java.util.List;

/**
 *
 * @author DanilinS
 */
public class HtTextBox extends javax.swing.JFrame {

    /** Creates new form HtTextBox */
    public HtTextBox(List<HtDrawableObject.Text> text_obj_list, long ttime) {
        initComponents();

				//
				String ttime_str = Utils.formatDateTime(ttime);
				jTextField1.setText(ttime_str);

				jContentTextArea.setText(Utils.createTextFromAllTextObjects(text_obj_list, ttime));
				
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jTextField1 = new javax.swing.JTextField();
    jScrollPane1 = new javax.swing.JScrollPane();
    jContentTextArea = new javax.swing.JTextArea();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setName("Form"); // NOI18N

    org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(com.fin.htraderhelper.HtChartingApp.class).getContext().getResourceMap(HtTextBox.class);
    jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
    jLabel1.setName("jLabel1"); // NOI18N

    jTextField1.setEditable(false);
    jTextField1.setText(resourceMap.getString("jTextField1.text")); // NOI18N
    jTextField1.setName("jTextField1"); // NOI18N

    jScrollPane1.setName("jScrollPane1"); // NOI18N

    jContentTextArea.setColumns(20);
    jContentTextArea.setFont(resourceMap.getFont("jContentTextArea.font")); // NOI18N
    jContentTextArea.setRows(5);
    jContentTextArea.setName("jContentTextArea"); // NOI18N
    jScrollPane1.setViewportView(jContentTextArea);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(466, Short.MAX_VALUE))
      .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 651, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel1)
          .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JTextArea jContentTextArea;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextField jTextField1;
  // End of variables declaration//GEN-END:variables

}
